fail_fast: true

repos:
  - repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
    - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
     - id: mypy
       files: ^(mypackage/|tests/)
       additional_dependencies:
        - "pydantic>=2.5"

default_language_version:
    python: python3.11
