services:
  main:
    container_name: main_unit_tests
    extends:
      file: base.yml
      service: main
    environment:
      - UNIT_TEST=true
      - HTTP_LOGGING_HOST
      - HTTP_LOGGING_PATH         
    networks:
      - cms_unit_tests

networks:
  cms_unit_tests:
